# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- task: SendGridEmail@2
  inputs:
    SendGridApiKey: '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'
    FromAddress: 'abraham1aguirre@gmail.com'
    ToAddresses: 'abraham1aguirre@gmail.com'
    Subject: 'Prueba'
    emailBodyFormat: 'InLine'
    EmailBody: 'hola'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
